// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './global.css'
import CaptivePortal from '@/components/CaptivePortal' // Import

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CaptivePortal />  {/* Add the component here */}
        {children}
      </body>
    </html>
  )
}