// /home/ashben/www/html/tipics/nextjs-test-app/app/layout.tsx

import { Inter } from 'next/font/google'
import './global.css'
import CaptivePortal from '../components/CaptivePortal'; // Corrected relative import

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <CaptivePortal/>{/*Render the component */}
        </body>
    </html>
  )
}